// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: api/v1/kvpb/general_kv.proto

package kvpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GeneralKVServiceClient is the client API for GeneralKVService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GeneralKVServiceClient interface {
	// GetAllKeys returns all the keys.
	// Uses the database sent in gRPC metadata or the default database if omitted.
	GetAllKeys(ctx context.Context, in *GetAllKeysRequest, opts ...grpc.CallOption) (*GetAllKeysResponse, error)
	// GetKeyType returns the data type of the value a key is holding.
	// Uses the database sent in gRPC metadata or the default database if omitted.
	GetKeyType(ctx context.Context, in *GetKeyTypeRequest, opts ...grpc.CallOption) (*GetKeyTypeResponse, error)
	// DeleteKeys deletes the specified keys and the values they are holding.
	// Ignores keys that do not exist.
	// Uses the database sent in gRPC metadata or the default database if omitted.
	DeleteKeys(ctx context.Context, in *DeleteKeysRequest, opts ...grpc.CallOption) (*DeleteKeysResponse, error)
	// DeleteAllKeys deletes all the keys.
	// Uses the database sent in gRPC metadata or the default database if omitted.
	DeleteAllKeys(ctx context.Context, in *DeleteAllKeysRequest, opts ...grpc.CallOption) (*DeleteAllKeysResponse, error)
}

type generalKVServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewGeneralKVServiceClient(cc grpc.ClientConnInterface) GeneralKVServiceClient {
	return &generalKVServiceClient{cc}
}

func (c *generalKVServiceClient) GetAllKeys(ctx context.Context, in *GetAllKeysRequest, opts ...grpc.CallOption) (*GetAllKeysResponse, error) {
	out := new(GetAllKeysResponse)
	err := c.cc.Invoke(ctx, "/api.v1.kvpb.GeneralKVService/GetAllKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *generalKVServiceClient) GetKeyType(ctx context.Context, in *GetKeyTypeRequest, opts ...grpc.CallOption) (*GetKeyTypeResponse, error) {
	out := new(GetKeyTypeResponse)
	err := c.cc.Invoke(ctx, "/api.v1.kvpb.GeneralKVService/GetKeyType", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *generalKVServiceClient) DeleteKeys(ctx context.Context, in *DeleteKeysRequest, opts ...grpc.CallOption) (*DeleteKeysResponse, error) {
	out := new(DeleteKeysResponse)
	err := c.cc.Invoke(ctx, "/api.v1.kvpb.GeneralKVService/DeleteKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *generalKVServiceClient) DeleteAllKeys(ctx context.Context, in *DeleteAllKeysRequest, opts ...grpc.CallOption) (*DeleteAllKeysResponse, error) {
	out := new(DeleteAllKeysResponse)
	err := c.cc.Invoke(ctx, "/api.v1.kvpb.GeneralKVService/DeleteAllKeys", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GeneralKVServiceServer is the server API for GeneralKVService service.
// All implementations must embed UnimplementedGeneralKVServiceServer
// for forward compatibility
type GeneralKVServiceServer interface {
	// GetAllKeys returns all the keys.
	// Uses the database sent in gRPC metadata or the default database if omitted.
	GetAllKeys(context.Context, *GetAllKeysRequest) (*GetAllKeysResponse, error)
	// GetKeyType returns the data type of the value a key is holding.
	// Uses the database sent in gRPC metadata or the default database if omitted.
	GetKeyType(context.Context, *GetKeyTypeRequest) (*GetKeyTypeResponse, error)
	// DeleteKeys deletes the specified keys and the values they are holding.
	// Ignores keys that do not exist.
	// Uses the database sent in gRPC metadata or the default database if omitted.
	DeleteKeys(context.Context, *DeleteKeysRequest) (*DeleteKeysResponse, error)
	// DeleteAllKeys deletes all the keys.
	// Uses the database sent in gRPC metadata or the default database if omitted.
	DeleteAllKeys(context.Context, *DeleteAllKeysRequest) (*DeleteAllKeysResponse, error)
	mustEmbedUnimplementedGeneralKVServiceServer()
}

// UnimplementedGeneralKVServiceServer must be embedded to have forward compatible implementations.
type UnimplementedGeneralKVServiceServer struct {
}

func (UnimplementedGeneralKVServiceServer) GetAllKeys(context.Context, *GetAllKeysRequest) (*GetAllKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllKeys not implemented")
}
func (UnimplementedGeneralKVServiceServer) GetKeyType(context.Context, *GetKeyTypeRequest) (*GetKeyTypeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyType not implemented")
}
func (UnimplementedGeneralKVServiceServer) DeleteKeys(context.Context, *DeleteKeysRequest) (*DeleteKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteKeys not implemented")
}
func (UnimplementedGeneralKVServiceServer) DeleteAllKeys(context.Context, *DeleteAllKeysRequest) (*DeleteAllKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteAllKeys not implemented")
}
func (UnimplementedGeneralKVServiceServer) mustEmbedUnimplementedGeneralKVServiceServer() {}

// UnsafeGeneralKVServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GeneralKVServiceServer will
// result in compilation errors.
type UnsafeGeneralKVServiceServer interface {
	mustEmbedUnimplementedGeneralKVServiceServer()
}

func RegisterGeneralKVServiceServer(s grpc.ServiceRegistrar, srv GeneralKVServiceServer) {
	s.RegisterService(&GeneralKVService_ServiceDesc, srv)
}

func _GeneralKVService_GetAllKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneralKVServiceServer).GetAllKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.kvpb.GeneralKVService/GetAllKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneralKVServiceServer).GetAllKeys(ctx, req.(*GetAllKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeneralKVService_GetKeyType_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyTypeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneralKVServiceServer).GetKeyType(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.kvpb.GeneralKVService/GetKeyType",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneralKVServiceServer).GetKeyType(ctx, req.(*GetKeyTypeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeneralKVService_DeleteKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneralKVServiceServer).DeleteKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.kvpb.GeneralKVService/DeleteKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneralKVServiceServer).DeleteKeys(ctx, req.(*DeleteKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GeneralKVService_DeleteAllKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAllKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GeneralKVServiceServer).DeleteAllKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v1.kvpb.GeneralKVService/DeleteAllKeys",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GeneralKVServiceServer).DeleteAllKeys(ctx, req.(*DeleteAllKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GeneralKVService_ServiceDesc is the grpc.ServiceDesc for GeneralKVService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GeneralKVService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v1.kvpb.GeneralKVService",
	HandlerType: (*GeneralKVServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAllKeys",
			Handler:    _GeneralKVService_GetAllKeys_Handler,
		},
		{
			MethodName: "GetKeyType",
			Handler:    _GeneralKVService_GetKeyType_Handler,
		},
		{
			MethodName: "DeleteKeys",
			Handler:    _GeneralKVService_DeleteKeys_Handler,
		},
		{
			MethodName: "DeleteAllKeys",
			Handler:    _GeneralKVService_DeleteAllKeys_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v1/kvpb/general_kv.proto",
}
