FROM golang:1.22.0-alpine as builder
WORKDIR /src
COPY . .
RUN go mod download

WORKDIR /src/cmd/hakjserver
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o hakjserver .

FROM alpine:latest
WORKDIR /hakjdb
COPY --from=builder /src/cmd/hakjserver/hakjserver .
CMD ["./hakjserver"]
