FROM golang:1.22.0-alpine as builder
WORKDIR /src
COPY . .
RUN go mod download

WORKDIR /src/cmd/kvdbserver
RUN CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o kvdbserver .

FROM debian:bookworm-slim
WORKDIR /kvdb
COPY --from=builder /src/cmd/kvdbserver/kvdbserver .
CMD ["./kvdbserver"]