#!/bin/bash

# This script generates and copies the autogenerated kvdbctl command documentations
# to docs/kvdbctl-commands/generated/ directory.
# The kvdbctl program needs to be in bin/kvdbctl/ directory before running this.
# Execute this script in the root of the project.

./bin/kvdbctl/kvdbctl
cp -r bin/kvdbctl/generated-docs/* docs/kvdbctl-commands/generated
