#!/bin/bash

# This script generates and copies the autogenerated hakjctl command documentations
# to docs/hakjctl-commands/generated/ directory.
# The hakjctl binary needs to be in bin/hakjctl/ directory before running this.
# hakjctl binary can be built to the correct directory by running build_hakjctl.sh script from the project root.
# Execute this script from the project root.

./bin/hakjctl/hakjctl
cp -r bin/hakjctl/generated-docs/* docs/hakjctl-commands/generated
