// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: api/v0/kvpb/hashmap_kv.proto

package kvpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// HashMapKVServiceClient is the client API for HashMapKVService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HashMapKVServiceClient interface {
	// SetHashMap sets the specified fields and their values in the HashMap stored at a key.
	// If the specified fields exist, they will be overwritten with the new values.
	// Creates the key if it doesn't exist. Overwrites the key if it is holding a value of another data type.
	// Uses the database sent in gRPC metadata or the default database if omitted.
	SetHashMap(ctx context.Context, in *SetHashMapRequest, opts ...grpc.CallOption) (*SetHashMapResponse, error)
	// GetHashMapFieldValues returns the values of the specified fields in the HashMap stored at a key.
	// Uses the database sent in gRPC metadata or the default database if omitted.
	GetHashMapFieldValues(ctx context.Context, in *GetHashMapFieldValuesRequest, opts ...grpc.CallOption) (*GetHashMapFieldValuesResponse, error)
	// GetAllHashMapFieldsAndValues returns all the fields and values of the HashMap stored at a key.
	// Uses the database sent in gRPC metadata or the default database if omitted.
	GetAllHashMapFieldsAndValues(ctx context.Context, in *GetAllHashMapFieldsAndValuesRequest, opts ...grpc.CallOption) (*GetAllHashMapFieldsAndValuesResponse, error)
	// DeleteHashMapFields removes the specified fields from the HashMap stored at a key.
	// Ignores fields that do not exist.
	// Uses the database sent in gRPC metadata or the default database if omitted.
	DeleteHashMapFields(ctx context.Context, in *DeleteHashMapFieldsRequest, opts ...grpc.CallOption) (*DeleteHashMapFieldsResponse, error)
}

type hashMapKVServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewHashMapKVServiceClient(cc grpc.ClientConnInterface) HashMapKVServiceClient {
	return &hashMapKVServiceClient{cc}
}

func (c *hashMapKVServiceClient) SetHashMap(ctx context.Context, in *SetHashMapRequest, opts ...grpc.CallOption) (*SetHashMapResponse, error) {
	out := new(SetHashMapResponse)
	err := c.cc.Invoke(ctx, "/api.v0.kvpb.HashMapKVService/SetHashMap", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashMapKVServiceClient) GetHashMapFieldValues(ctx context.Context, in *GetHashMapFieldValuesRequest, opts ...grpc.CallOption) (*GetHashMapFieldValuesResponse, error) {
	out := new(GetHashMapFieldValuesResponse)
	err := c.cc.Invoke(ctx, "/api.v0.kvpb.HashMapKVService/GetHashMapFieldValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashMapKVServiceClient) GetAllHashMapFieldsAndValues(ctx context.Context, in *GetAllHashMapFieldsAndValuesRequest, opts ...grpc.CallOption) (*GetAllHashMapFieldsAndValuesResponse, error) {
	out := new(GetAllHashMapFieldsAndValuesResponse)
	err := c.cc.Invoke(ctx, "/api.v0.kvpb.HashMapKVService/GetAllHashMapFieldsAndValues", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashMapKVServiceClient) DeleteHashMapFields(ctx context.Context, in *DeleteHashMapFieldsRequest, opts ...grpc.CallOption) (*DeleteHashMapFieldsResponse, error) {
	out := new(DeleteHashMapFieldsResponse)
	err := c.cc.Invoke(ctx, "/api.v0.kvpb.HashMapKVService/DeleteHashMapFields", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HashMapKVServiceServer is the server API for HashMapKVService service.
// All implementations must embed UnimplementedHashMapKVServiceServer
// for forward compatibility
type HashMapKVServiceServer interface {
	// SetHashMap sets the specified fields and their values in the HashMap stored at a key.
	// If the specified fields exist, they will be overwritten with the new values.
	// Creates the key if it doesn't exist. Overwrites the key if it is holding a value of another data type.
	// Uses the database sent in gRPC metadata or the default database if omitted.
	SetHashMap(context.Context, *SetHashMapRequest) (*SetHashMapResponse, error)
	// GetHashMapFieldValues returns the values of the specified fields in the HashMap stored at a key.
	// Uses the database sent in gRPC metadata or the default database if omitted.
	GetHashMapFieldValues(context.Context, *GetHashMapFieldValuesRequest) (*GetHashMapFieldValuesResponse, error)
	// GetAllHashMapFieldsAndValues returns all the fields and values of the HashMap stored at a key.
	// Uses the database sent in gRPC metadata or the default database if omitted.
	GetAllHashMapFieldsAndValues(context.Context, *GetAllHashMapFieldsAndValuesRequest) (*GetAllHashMapFieldsAndValuesResponse, error)
	// DeleteHashMapFields removes the specified fields from the HashMap stored at a key.
	// Ignores fields that do not exist.
	// Uses the database sent in gRPC metadata or the default database if omitted.
	DeleteHashMapFields(context.Context, *DeleteHashMapFieldsRequest) (*DeleteHashMapFieldsResponse, error)
	mustEmbedUnimplementedHashMapKVServiceServer()
}

// UnimplementedHashMapKVServiceServer must be embedded to have forward compatible implementations.
type UnimplementedHashMapKVServiceServer struct {
}

func (UnimplementedHashMapKVServiceServer) SetHashMap(context.Context, *SetHashMapRequest) (*SetHashMapResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetHashMap not implemented")
}
func (UnimplementedHashMapKVServiceServer) GetHashMapFieldValues(context.Context, *GetHashMapFieldValuesRequest) (*GetHashMapFieldValuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHashMapFieldValues not implemented")
}
func (UnimplementedHashMapKVServiceServer) GetAllHashMapFieldsAndValues(context.Context, *GetAllHashMapFieldsAndValuesRequest) (*GetAllHashMapFieldsAndValuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllHashMapFieldsAndValues not implemented")
}
func (UnimplementedHashMapKVServiceServer) DeleteHashMapFields(context.Context, *DeleteHashMapFieldsRequest) (*DeleteHashMapFieldsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteHashMapFields not implemented")
}
func (UnimplementedHashMapKVServiceServer) mustEmbedUnimplementedHashMapKVServiceServer() {}

// UnsafeHashMapKVServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HashMapKVServiceServer will
// result in compilation errors.
type UnsafeHashMapKVServiceServer interface {
	mustEmbedUnimplementedHashMapKVServiceServer()
}

func RegisterHashMapKVServiceServer(s grpc.ServiceRegistrar, srv HashMapKVServiceServer) {
	s.RegisterService(&HashMapKVService_ServiceDesc, srv)
}

func _HashMapKVService_SetHashMap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetHashMapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashMapKVServiceServer).SetHashMap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v0.kvpb.HashMapKVService/SetHashMap",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashMapKVServiceServer).SetHashMap(ctx, req.(*SetHashMapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashMapKVService_GetHashMapFieldValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetHashMapFieldValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashMapKVServiceServer).GetHashMapFieldValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v0.kvpb.HashMapKVService/GetHashMapFieldValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashMapKVServiceServer).GetHashMapFieldValues(ctx, req.(*GetHashMapFieldValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashMapKVService_GetAllHashMapFieldsAndValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllHashMapFieldsAndValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashMapKVServiceServer).GetAllHashMapFieldsAndValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v0.kvpb.HashMapKVService/GetAllHashMapFieldsAndValues",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashMapKVServiceServer).GetAllHashMapFieldsAndValues(ctx, req.(*GetAllHashMapFieldsAndValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashMapKVService_DeleteHashMapFields_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteHashMapFieldsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashMapKVServiceServer).DeleteHashMapFields(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v0.kvpb.HashMapKVService/DeleteHashMapFields",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashMapKVServiceServer).DeleteHashMapFields(ctx, req.(*DeleteHashMapFieldsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// HashMapKVService_ServiceDesc is the grpc.ServiceDesc for HashMapKVService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HashMapKVService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v0.kvpb.HashMapKVService",
	HandlerType: (*HashMapKVServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetHashMap",
			Handler:    _HashMapKVService_SetHashMap_Handler,
		},
		{
			MethodName: "GetHashMapFieldValues",
			Handler:    _HashMapKVService_GetHashMapFieldValues_Handler,
		},
		{
			MethodName: "GetAllHashMapFieldsAndValues",
			Handler:    _HashMapKVService_GetAllHashMapFieldsAndValues_Handler,
		},
		{
			MethodName: "DeleteHashMapFields",
			Handler:    _HashMapKVService_DeleteHashMapFields_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v0/kvpb/hashmap_kv.proto",
}
