// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v5.27.1
// source: api/v0/kvpb/string_kv.proto

package kvpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// StringKVServiceClient is the client API for StringKVService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StringKVServiceClient interface {
	// SetString sets a key to hold a String value. Creates the key if it doesn't exist.
	// Overwrites the key if it is holding a value of another data type.
	// Uses the database sent in gRPC metadata or the default database if omitted.
	SetString(ctx context.Context, in *SetStringRequest, opts ...grpc.CallOption) (*SetStringResponse, error)
	// GetString returns the value a String key is holding.
	// Uses the database sent in gRPC metadata or the default database if omitted.
	GetString(ctx context.Context, in *GetStringRequest, opts ...grpc.CallOption) (*GetStringResponse, error)
}

type stringKVServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewStringKVServiceClient(cc grpc.ClientConnInterface) StringKVServiceClient {
	return &stringKVServiceClient{cc}
}

func (c *stringKVServiceClient) SetString(ctx context.Context, in *SetStringRequest, opts ...grpc.CallOption) (*SetStringResponse, error) {
	out := new(SetStringResponse)
	err := c.cc.Invoke(ctx, "/api.v0.kvpb.StringKVService/SetString", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *stringKVServiceClient) GetString(ctx context.Context, in *GetStringRequest, opts ...grpc.CallOption) (*GetStringResponse, error) {
	out := new(GetStringResponse)
	err := c.cc.Invoke(ctx, "/api.v0.kvpb.StringKVService/GetString", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StringKVServiceServer is the server API for StringKVService service.
// All implementations must embed UnimplementedStringKVServiceServer
// for forward compatibility
type StringKVServiceServer interface {
	// SetString sets a key to hold a String value. Creates the key if it doesn't exist.
	// Overwrites the key if it is holding a value of another data type.
	// Uses the database sent in gRPC metadata or the default database if omitted.
	SetString(context.Context, *SetStringRequest) (*SetStringResponse, error)
	// GetString returns the value a String key is holding.
	// Uses the database sent in gRPC metadata or the default database if omitted.
	GetString(context.Context, *GetStringRequest) (*GetStringResponse, error)
	mustEmbedUnimplementedStringKVServiceServer()
}

// UnimplementedStringKVServiceServer must be embedded to have forward compatible implementations.
type UnimplementedStringKVServiceServer struct {
}

func (UnimplementedStringKVServiceServer) SetString(context.Context, *SetStringRequest) (*SetStringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetString not implemented")
}
func (UnimplementedStringKVServiceServer) GetString(context.Context, *GetStringRequest) (*GetStringResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetString not implemented")
}
func (UnimplementedStringKVServiceServer) mustEmbedUnimplementedStringKVServiceServer() {}

// UnsafeStringKVServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StringKVServiceServer will
// result in compilation errors.
type UnsafeStringKVServiceServer interface {
	mustEmbedUnimplementedStringKVServiceServer()
}

func RegisterStringKVServiceServer(s grpc.ServiceRegistrar, srv StringKVServiceServer) {
	s.RegisterService(&StringKVService_ServiceDesc, srv)
}

func _StringKVService_SetString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetStringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StringKVServiceServer).SetString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v0.kvpb.StringKVService/SetString",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StringKVServiceServer).SetString(ctx, req.(*SetStringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StringKVService_GetString_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStringRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StringKVServiceServer).GetString(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/api.v0.kvpb.StringKVService/GetString",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StringKVServiceServer).GetString(ctx, req.(*GetStringRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StringKVService_ServiceDesc is the grpc.ServiceDesc for StringKVService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StringKVService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.v0.kvpb.StringKVService",
	HandlerType: (*StringKVServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetString",
			Handler:    _StringKVService_SetString_Handler,
		},
		{
			MethodName: "GetString",
			Handler:    _StringKVService_GetString_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/v0/kvpb/string_kv.proto",
}
