# This workflow will build a golang project and run tests
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Set permissions
      run: chmod +x ./build_hakjserver.sh ./build_hakjctl.sh

    - name: Build hakjserver
      run: ./build_hakjserver.sh

    - name: Build hakjctl
      run: ./build_hakjctl.sh

    - name: Test
      run: go test -v ./...
