# This workflow will push releases with GoReleaser and publish Docker images
# For more information see:
# https://goreleaser.com/ci/actions/
# https://docs.docker.com/build/ci/github-actions/

name: release

on:
  pull_request:
  push:
    # run only against tags
    tags:
      - "*"

permissions:
  contents: write
  # packages: write
  # issues: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.22'

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          # either 'goreleaser' (default) or 'goreleaser-pro'
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GORELEASER_GITHUB_TOKEN }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Debian bookworm based image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.bookworm
          push: true
          tags: |
            hakj/kvdb:latest
            hakj/kvdb:${{ github.ref_name }}
            hakj/kvdb:bookworm
            hakj/kvdb:${{ github.ref_name }}-bookworm
      
      - name: Build and push Alpine Linux based image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile.alpine
          push: true
          tags: |
            hakj/kvdb:alpine
            hakj/kvdb:${{ github.ref_name }}-alpine